sudo: required
language: c

env:
  - CABALVER=2.4 GHCVER=8.0.2
  - CABALVER=2.4 GHCVER=8.2.1
  - CABALVER=2.4 GHCVER=8.4.1
  - CABALVER=2.4 GHCVER=8.4.2
  - CABALVER=2.4 GHCVER=8.4.3
  - CABALVER=2.4 GHCVER=8.4.4
  - CABALVER=2.4 GHCVER=8.6.1
  - CABALVER=2.4 GHCVER=8.6.2
  - CABALVER=2.4 GHCVER=8.6.3
  - CABALVER=2.4 GHCVER=8.6.4

install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
  - cabal update
  - cabal install --only-dependencies --enable-tests

script:
  - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
